'use client';
import { zodResolver } from '@hookform/resolvers/zod';
import { useForm } from 'react-hook-form';
import * as z from 'zod';
import { useState } from 'react';

import { Button } from '@/components/ui/button';
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Calendar } from '@/components/ui/calendar';
import { CalendarIcon, Sparkles } from 'lucide-react';
import { cn } from '@/lib/utils';
import { format } from 'date-fns';
import { useToast } from '@/hooks/use-toast';
import { useRouter } from 'next/navigation';
import { generateTitleAction, classifyFoodAction } from '@/app/actions';

const formSchema = z.object({
  title: z.string().min(5, 'Title must be at least 5 characters.'),
  description: z.string().min(10, 'Description must be at least 10 characters.'),
  plates: z.coerce.number().min(1, 'Must be at least 1 plate.'),
  category: z.enum(['Veg', 'Non-Veg']),
  visibility: z.enum(['Public', 'College']),
  expiry: z.date({ required_error: 'Expiry date is required.' }),
  location: z.string().min(5, 'Location is required.'),
});

type AiLoadingState = 'title' | 'category' | null;

export default function NewDonationPage() {
  const { toast } = useToast();
  const router = useRouter();
  const [aiLoading, setAiLoading] = useState<AiLoadingState>(null);

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      plates: 1,
      visibility: 'College',
      expiry: new Date(new Date().getTime() + 3 * 60 * 60 * 1000), // 3 hours from now
    },
  });

  const handleGenerateTitle = async () => {
    const description = form.getValues('description');
    if (!description) {
      toast({ variant: 'destructive', description: 'Please enter a description first to generate a title.' });
      return;
    }
    setAiLoading('title');
    const result = await generateTitleAction(description);
    if (result.success && result.title) {
      form.setValue('title', result.title);
      toast({ description: 'Title generated by AI!' });
    } else {
      toast({ variant: 'destructive', description: result.error });
    }
    setAiLoading(null);
  };
  
  const handleClassifyFood = async () => {
    const title = form.getValues('title');
    const description = form.getValues('description');
     if (!title || !description) {
      toast({ variant: 'destructive', description: 'Please enter a title and description first to classify.' });
      return;
    }
    setAiLoading('category');
    const result = await classifyFoodAction(title, description);
    if (result.success && result.category) {
        form.setValue('category', result.category);
        toast({ description: `Food classified as ${result.category} by AI!` });
    } else {
        toast({ variant: 'destructive', description: result.error });
    }
    setAiLoading(null);
  }

  function onSubmit(values: z.infer<typeof formSchema>) {
    console.log(values);
    toast({
      title: 'Donation Posted!',
      description: 'Your donation is now visible to others.',
    });
    router.push('/home');
  }

  return (
    <div className="container mx-auto max-w-2xl py-8">
      <Card className="shadow-lg">
        <CardHeader>
          <CardTitle className="text-2xl font-headline">Create a New Donation</CardTitle>
          <CardDescription>Fill out the details below to post your extra food.</CardDescription>
        </CardHeader>
        <CardContent>
          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
              <FormField
                control={form.control}
                name="title"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Title</FormLabel>
                    <div className="flex gap-2">
                      <FormControl>
                        <Input placeholder="e.g., 10 Plates of Paneer Butter Masala" {...field} />
                      </FormControl>
                      <Button type="button" variant="outline" size="icon" onClick={handleGenerateTitle} disabled={aiLoading === 'title'}>
                        {aiLoading === 'title' ? <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-current"></div> : <Sparkles className="h-4 w-4" />}
                        <span className="sr-only">Generate Title</span>
                      </Button>
                    </div>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="description"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Description</FormLabel>
                    <FormControl>
                      <Textarea placeholder="Describe the food, its condition, and any allergens." {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                 <FormField
                  control={form.control}
                  name="category"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Category</FormLabel>
                      <div className="flex gap-2">
                        <Select onValueChange={field.onChange} defaultValue={field.value}>
                          <FormControl>
                            <SelectTrigger>
                              <SelectValue placeholder="Select food type" />
                            </SelectTrigger>
                          </FormControl>
                          <SelectContent>
                            <SelectItem value="Veg">Veg</SelectItem>
                            <SelectItem value="Non-Veg">Non-Veg</SelectItem>
                          </SelectContent>
                        </Select>
                        <Button type="button" variant="outline" size="icon" onClick={handleClassifyFood} disabled={aiLoading === 'category'}>
                            {aiLoading === 'category' ? <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-current"></div> : <Sparkles className="h-4 w-4" />}
                          <span className="sr-only">Classify Food</span>
                        </Button>
                      </div>
                      <FormMessage />
                    </FormItem>
                  )}
                />
                 <FormField
                  control={form.control}
                  name="plates"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Number of Plates</FormLabel>
                      <FormControl>
                        <Input type="number" {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <FormField
                  control={form.control}
                  name="expiry"
                  render={({ field }) => (
                    <FormItem className="flex flex-col">
                      <FormLabel>Expires On</FormLabel>
                      <Popover>
                        <PopoverTrigger asChild>
                          <FormControl>
                            <Button
                              variant={'outline'}
                              className={cn(
                                'w-full pl-3 text-left font-normal',
                                !field.value && 'text-muted-foreground'
                              )}
                            >
                              {field.value ? (
                                format(field.value, 'PPP')
                              ) : (
                                <span>Pick a date</span>
                              )}
                              <CalendarIcon className="ml-auto h-4 w-4 opacity-50" />
                            </Button>
                          </FormControl>
                        </PopoverTrigger>
                        <PopoverContent className="w-auto p-0" align="start">
                          <Calendar
                            mode="single"
                            selected={field.value}
                            onSelect={field.onChange}
                            disabled={(date) => date < new Date() || date < new Date('1900-01-01')}
                            initialFocus
                          />
                        </PopoverContent>
                      </Popover>
                      <FormMessage />
                    </FormItem>
                  )}
                />
                <FormField
                  control={form.control}
                  name="visibility"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Visibility</FormLabel>
                      <Select onValueChange={field.onChange} defaultValue={field.value}>
                        <FormControl>
                          <SelectTrigger>
                            <SelectValue placeholder="Select visibility" />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          <SelectItem value="College">College Only</SelectItem>
                          <SelectItem value="Public">Public</SelectItem>
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>

               <FormField
                control={form.control}
                name="location"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Pickup Location</FormLabel>
                    <FormControl>
                      <Input placeholder="e.g., Hostel Block C, Room 201" {...field} />
                    </FormControl>
                    <FormDescription>
                        Be as specific as possible for easy pickup.
                    </FormDescription>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <Button type="submit" size="lg" className="w-full">Post Donation</Button>
            </form>
          </Form>
        </CardContent>
      </Card>
    </div>
  );
}
